[project]
name = "mo-flow-sg"
version = "0.1.0"
description = "Flow matching implementation for the paper 'Flow Matching for Convective-scale Precipitation Downscaling'"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azureml-mlflow==1.55.0",
    "mlflow-skinny==2.16.1",
    "torch==2.8.0",
    "xarray",
    "einops",
    "numpy",
    "netCDF4",
    "dask",
    "scipy",
    "zarr",
    "pytz",
    "pydantic",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 100
exclude = [
  ".git",
  ".pytest_cache",
  ".ruff_cache",
  ".vscode",
  "_build",
  "build",
  "dist",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
